# Novel AI Agent Configuration
llm:
  provider: "ollama"  # Supported: ollama, openai, anthropic, google, azure, cohere, huggingface, together, groq, deepseek, moonshot, zhipu, baidu, alibaba
  model: "llama3"
  base_url: "http://localhost:11434"  # Optional: will use default if not specified
  api_key: null  # Optional: will use environment variable if not specified
  temperature: 0.8
  max_tokens: 4096

# API Keys Configuration (alternatively set as environment variables)
api_keys:
  openai: null  # Set OPENAI_API_KEY environment variable or specify here
  anthropic: null  # Set ANTHROPIC_API_KEY environment variable or specify here
  google: null  # Set GOOGLE_API_KEY environment variable or specify here
  azure: null  # Set AZURE_API_KEY environment variable or specify here
  cohere: null  # Set COHERE_API_KEY environment variable or specify here
  huggingface: null  # Set HUGGINGFACE_API_KEY environment variable or specify here
  together: null  # Set TOGETHER_API_KEY environment variable or specify here
  groq: null  # Set GROQ_API_KEY environment variable or specify here
  deepseek: null  # Set DEEPSEEK_API_KEY environment variable or specify here
  moonshot: null  # Set MOONSHOT_API_KEY environment variable or specify here
  zhipu: null  # Set ZHIPU_API_KEY environment variable or specify here
  baidu: null  # Set BAIDU_API_KEY environment variable or specify here
  alibaba: null  # Set ALIBABA_API_KEY environment variable or specify here

story:
  target_length: 5000000  # 5 million words
  chapter_length: 5000    # words per chapter
  save_interval: 1000     # save every N words
  output_dir: "output"
  
agents:
  max_agents: 10
  director_enabled: true
  character_types:
    - "protagonist"
    - "antagonist"
    - "supporting"
    - "narrator"

evolution:
  enabled: true
  mutation_rate: 0.1
  evaluation_interval: 10000  # words
  backup_generations: 5
  
simulation:
  world_complexity: "medium"
  event_frequency: 0.3
  environment_changes: true
  
web_interface:
  host: "0.0.0.0"
  port: 12000
  enable_cors: true