# Novel AI Agent Configuration
llm:
  provider: "ollama"  # Supported: ollama, openai, anthropic, google, azure, cohere, huggingface, together, groq, deepseek, moonshot, zhipu, baidu, alibaba
  model: "llama3"
  base_url: "http://localhost:11434"  # Optional: will use default if not specified
  api_key: null  # Optional: will use environment variable if not specified
  temperature: 0.8
  max_tokens: 4096

# API Keys Configuration (alternatively set as environment variables)
api_keys:
  openai: null  # Set OPENAI_API_KEY environment variable or specify here
  anthropic: null  # Set ANTHROPIC_API_KEY environment variable or specify here
  google: null  # Set GOOGLE_API_KEY environment variable or specify here
  azure: null  # Set AZURE_API_KEY environment variable or specify here
  cohere: null  # Set COHERE_API_KEY environment variable or specify here
  huggingface: null  # Set HUGGINGFACE_API_KEY environment variable or specify here
  together: null  # Set TOGETHER_API_KEY environment variable or specify here
  groq: null  # Set GROQ_API_KEY environment variable or specify here
  deepseek: null  # Set DEEPSEEK_API_KEY environment variable or specify here
  moonshot: null  # Set MOONSHOT_API_KEY environment variable or specify here
  zhipu: null  # Set ZHIPU_API_KEY environment variable or specify here
  baidu: null  # Set BAIDU_API_KEY environment variable or specify here
  alibaba: null  # Set ALIBABA_API_KEY environment variable or specify here

story:
  target_length: 5000000  # 5 million words
  chapter_length: 5000    # words per chapter
  save_interval: 1000     # save every N words
  output_dir: "output"
  
agents:
  max_agents: 10
  director_enabled: true
  character_types:
    - "protagonist"
    - "antagonist"
    - "supporting"
    - "narrator"

evolution:
  enabled: true
  mutation_rate: 0.1
  evaluation_interval: 10000  # words
  backup_generations: 5
  
simulation:
  world_complexity: "medium"
  event_frequency: 0.3
  environment_changes: true
  
web_interface:
  host: "0.0.0.0"
  port: 12000
  enable_cors: true

# Multi-Agent System Configuration
multi_agent:
  enabled: true
  max_agents: 20
  default_agent_types:
    - "assistant"
    - "expert"
    - "creative"
    - "task"
  orchestration_strategy: "hierarchical"  # hierarchical, peer-to-peer, hybrid
  memory_enabled: true
  tool_usage_enabled: true
  communication_logging: true
  default_llm_temperature: 0.7
  default_max_tokens: 2048
  
  # Agent creation settings
  auto_create_agents: true
  agent_creation_threshold: 0.7
  
  # Task management settings
  task_decomposition_enabled: true
  max_concurrent_tasks: 10
  task_timeout_seconds: 300
  
  # Communication settings
  broadcast_enabled: true
  direct_communication_enabled: true
  message_queue_size: 100
  
  # Memory settings
  memory_retention_days: 30
  memory_importance_threshold: 0.3
  
  # Tool settings
  default_tools_enabled: true
  tool_usage_logging: true
  
  # Web interface settings
  web_visualization_enabled: true
  agent_interaction_enabled: true