# Universal AI Agent System Configuration
# Minimizes hardcoding, maximizes flexibility through configuration

# LLM Configuration - The intelligence engine
llm:
  provider: "ollama"  # ollama, openai, anthropic, google, azure, cohere, etc.
  model: "llama3"
  base_url: "http://localhost:11434"
  api_key: null  # Will use environment variables if not specified
  temperature: 0.7  # Creativity level (0.0 - 1.0)
  max_tokens: 4096  # Maximum response length
  
# API Keys (alternatively set as environment variables)
api_keys:
  openai: null      # OPENAI_API_KEY
  anthropic: null   # ANTHROPIC_API_KEY
  google: null      # GOOGLE_API_KEY
  azure: null       # AZURE_API_KEY
  cohere: null      # COHERE_API_KEY
  huggingface: null # HUGGINGFACE_API_KEY
  together: null    # TOGETHER_API_KEY
  groq: null        # GROQ_API_KEY
  deepseek: null    # DEEPSEEK_API_KEY
  moonshot: null    # MOONSHOT_API_KEY
  zhipu: null       # ZHIPU_API_KEY
  baidu: null       # BAIDU_API_KEY
  alibaba: null     # ALIBABA_API_KEY

# Universal System Configuration
universal_system:
  # Core directories
  prompts_dir: "prompts"
  memory_dir: "memory"
  plugins_dir: "plugins"
  state_dir: "state"
  
  # System behavior
  auto_optimize: true           # Automatically optimize prompts and behavior
  self_improve: true           # Enable self-improvement capabilities
  adaptive_learning: true      # Learn from interactions
  pattern_recognition: true    # Recognize and learn patterns
  
  # Memory system
  memory:
    max_working_memories: 1000      # Working memory limit
    max_episodic_memories: 10000    # Episodic memory limit
    max_semantic_memories: 5000     # Semantic memory limit
    consolidation_interval: 300     # Seconds between consolidation
    importance_threshold: 0.3       # Minimum importance to persist
    cleanup_interval: 3600          # Seconds between cleanup
    
  # Communication system
  communication:
    message_history_limit: 10000    # Maximum messages to keep
    conversation_timeout: 3600      # Seconds before conversation expires
    broadcast_enabled: true         # Enable broadcast messages
    pattern_learning: true          # Learn communication patterns
    
  # Plugin system
  plugins:
    auto_generate: true             # Automatically generate needed plugins
    load_on_demand: true           # Load plugins when needed
    cache_generated: true          # Cache generated plugins
    optimization_enabled: true     # Optimize plugin performance
    
  # Agent system
  agents:
    max_agents: 100                # Maximum number of agents
    auto_create: true              # Automatically create agents for tasks
    load_balancing: true           # Balance tasks across agents
    capability_matching: true     # Match tasks to agent capabilities
    adaptation_enabled: true      # Allow agents to adapt
    
# Default Agent Templates
agent_templates:
  general:
    capabilities: ["general", "assistant"]
    description: "General purpose assistant agent"
    priority: 5
    
  creative:
    capabilities: ["creative", "writing", "artistic"]
    description: "Creative agent for artistic and writing tasks"
    priority: 6
    
  analytical:
    capabilities: ["analytical", "research", "data"]
    description: "Analytical agent for research and data tasks"
    priority: 6
    
  technical:
    capabilities: ["technical", "programming", "engineering"]
    description: "Technical agent for programming and engineering"
    priority: 7
    
  expert:
    capabilities: ["expert", "specialist", "domain"]
    description: "Expert agent for specialized domain knowledge"
    priority: 8

# Task Management
task_management:
  intelligent_routing: true       # Intelligently route tasks to best agents
  priority_scheduling: true      # Schedule tasks by priority
  load_balancing: true          # Balance load across agents
  timeout_seconds: 300          # Default task timeout
  retry_attempts: 3             # Number of retry attempts
  decomposition_enabled: true   # Break complex tasks into subtasks
  
# Web Interface Configuration
web_interface:
  enabled: false
  host: "0.0.0.0"
  port: 12000
  cors_enabled: true
  real_time_updates: true
  visualization_enabled: true
  
# Logging and Monitoring
logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR
  file: "universal_system.log"
  max_size_mb: 100
  backup_count: 5
  
monitoring:
  metrics_enabled: true
  performance_tracking: true
  usage_analytics: true
  health_checks: true
  
# Security
security:
  api_key_required: false       # Require API key for access
  rate_limiting: false          # Enable rate limiting
  input_validation: true        # Validate all inputs
  output_filtering: true        # Filter sensitive outputs
  
# Experimental Features
experimental:
  quantum_coherence: false      # Experimental quantum-inspired processing
  neural_plasticity: true      # Dynamic neural network adaptation
  consciousness_simulation: false # Experimental consciousness modeling
  temporal_reasoning: true      # Advanced temporal reasoning capabilities
  meta_cognition: true         # Self-awareness and meta-thinking
  
# Performance Optimization
performance:
  async_processing: true        # Use asynchronous processing
  parallel_execution: true     # Execute tasks in parallel when possible
  caching_enabled: true        # Cache frequently used data
  compression_enabled: true    # Compress stored data
  lazy_loading: true           # Load resources on demand
  
# Backup and Recovery
backup:
  enabled: true
  interval_hours: 24           # Backup every 24 hours
  retention_days: 30           # Keep backups for 30 days
  compression: true            # Compress backup files
  
# Integration Settings
integrations:
  external_apis: true          # Allow external API calls
  file_system_access: true    # Allow file system operations
  network_access: true        # Allow network operations
  database_access: false      # Allow database operations
  
# Development Settings
development:
  debug_mode: false            # Enable debug mode
  verbose_logging: false       # Enable verbose logging
  profiling_enabled: false    # Enable performance profiling
  testing_mode: false         # Enable testing mode