#!/usr/bin/env python3
import sys
import time
import html
from urllib.parse import urlparse


def make_bookmarks(lines, title="Imported bookmarks"):
    now = int(time.time())
    header = (
        "<!DOCTYPE NETSCAPE-Bookmark-file-1>\n"
        "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">\n"
        f"<!-- Generated by txt2bookmarks.py on {time.ctime(now)} -->\n"
        "<TITLE>Bookmarks</TITLE>\n"
        "<H1>Bookmarks</H1>\n"
        "<DL><p>\n"
        f"    <DT><H3 ADD_DATE=\"{now}\" LAST_MODIFIED=\"{now}\">{html.escape(title)}</H3>\n"
        "    <DL><p>\n"
    )
    footer = "    </DL><p>\n</DL><p>\n"

    body_lines = []
    count = 0
    seen = set()

    for line in lines:
        url = line.strip()
        parsed = urlparse(url)
        if not parsed.netloc or url in seen:
            continue
        seen.add(url)

        title_text = html.escape(url)
        add_date = int(time.time())
        a = f'        <DT><A HREF="{url}" ADD_DATE="{add_date}">{title_text}</A>\n'
        body_lines.append(a)
        count += 1

    return header + "".join(body_lines) + footer, count


def main():
    if len(sys.argv) < 2:
        print("Usage: python txt2bookmarks.py input.txt [output.html]")
        sys.exit(1)

    infile = sys.argv[1]
    outfile = sys.argv[2] if len(sys.argv) > 2 else "bookmarks.html"

    with open(infile, "r", encoding="utf-8") as f:
        lines = f.readlines()

    content, wrote = make_bookmarks(lines, title="Imported from " + infile)

    with open(outfile, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Wrote {outfile} with {wrote} entries.")


if __name__ == "__main__":
    main()
